notifications:
  webhooks:
    urls:
      - https://kaltura.webhook.office.com/webhookb2/b992a7e1-5ff6-49a7-8d78-2f5e2909a982@0c503748-de3f-4e25-97e2-6819d53a42b6/TravisCI/8ee374eb79a8409fb0ca7cd27a49cf69/4779c8dc-fa74-44a9-9710-010265f09a25
    on_success: never
    on_cancel: never

conditions: v1
sudo: required
dist: xenial
language: node_js
node_js:
  - '17'
env:
  global:
    - NODE_OPTIONS="--openssl-legacy-provider"

addons:
  chrome: stable

services:
  - xvfb
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - export DISPLAY=:99.0

script:
  - set -ev
  - yarn install

stages:
  - Tests
  - Release

jobs:
  fast_finish: true
  include:
    # https://docs.travis-ci.com/user/build-stages/deploy-github-releases/
    - stage: Release
      if: (tag IS present)
      name: 'Release'
      script:
        - conventional-github-releaser -p angular -t $GH_TOKEN
    - stage: Release canary
      if: (branch = master) AND (type != pull_request) AND commit_message !~ /^chore\(release\)/ AND commit_message !~ /^(chore).*(update dist)$/
      name: 'Release canary'
      script:
        - git checkout master
        - yarn install
        - yarn run build && yarn commit:dist
        - git push https://$GH_TOKEN@github.com/kaltura/playkit-js-providers "master" > /dev/null 2>&1
    # Required tests
    - stage: Tests
      if: ((branch = master) OR (tag IS present) OR (type = pull_request)) AND commit_message !~ /^chore\(release\)/ AND commit_message !~ /^(chore).*(update dist)$/
      name: 'Running lint'
      script:
        - yarn run eslint
    - stage: Tests
      if: ((branch = master) OR (tag IS present) OR (type = pull_request)) AND commit_message !~ /^chore\(release\)/ AND commit_message !~ /^(chore).*(update dist)$/
      name: 'Running Flow type check'
      script:
        - yarn run flow
    - stage: Tests
      if: ((branch = master) OR (tag IS present) OR (type = pull_request)) AND commit_message !~ /^chore\(release\)/ AND commit_message !~ /^(chore).*(update dist)$/
      name: 'Running unit tests'
      script:
        - yarn run test
