conditions: v1
sudo: required
dist: xenial
language: node_js
node_js:
  - 'node'

addons:
  chrome: stable

services:
  - xvfb
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - export DISPLAY=:99.0

script:
  - set -ev
  - yarn install

stages:
  - Tests
  - Release

jobs:
  fast_finish: true
  include:
    # https://docs.travis-ci.com/user/build-stages/deploy-github-releases/
    - stage: Release
      if: (tag IS present)
      name: 'Release'
      script:
        - conventional-github-releaser -p angular -t $GH_TOKEN
    - stage: Release canary
      if: (branch = master) AND (type != pull_request) AND commit_message !~ /^chore\(release\)/ AND commit_message !~ /^(chore).*(update dist)$/
      name: 'Release canary'
      script:
        - git checkout master
        - yarn install
        - yarn run build && yarn commit:dist
        - git push https://$GH_TOKEN@github.com/kaltura/playkit-js-providers "master" > /dev/null 2>&1
    # Required tests
    - stage: Tests
      if: (branch = master) OR (tag IS present) OR (type = pull_request)
      name: 'Running lint'
      script:
        - yarn run eslint
    - stage: Tests
      if: (branch = master) OR (tag IS present) OR (type = pull_request)
      name: 'Running Flow type check'
      script:
        - yarn run flow
    - stage: Tests
      if: (branch = master) OR (tag IS present) OR (type = pull_request)
      name: 'Running unit tests'
      script:
        - yarn run test
