conditions: v1
sudo: required
dist: trusty
language: node_js
node_js:
  - "node"

git:
  depth: 500
  quiet: true

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - git checkout $TRAVIS_COMMIT
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

script:
  - yarn run lerna run build

stages:
  - Tests
  - Release canary
  - Release

jobs:
  fast_finish: true
  include:
    # https://docs.travis-ci.com/user/build-stages/deploy-github-releases/
    - stage: Release
      name: "Releasing a new version"
      if: branch = master AND commit_message =~ /^chore\(release\)/
      env: TRAVIS_MODE=release
      deploy:
        - provider: script
          script: yarn run lerna publish -- --no-git-reset --no-git-tag-version --no-push --from-git --yes
          skip_cleanup: true
          keep_history: true
          on:
            branch: master
    # publish canary package if on master
    - stage: Release canary
      if: (branch = master) AND (type != pull_request) AND commit_message !~ /^chore\(release\)/
      env: TRAVIS_MODE=releaseCanary
      deploy:
        - provider: script
          script: yarn run lerna publish -- --canary --preid canary --pre-dist-tag canary --no-git-reset --no-push --no-git-tag-version --yes
          skip_cleanup: true
          keep_history: true
          on:
            branch: master
    # Required tests
    - stage: Tests
      if: (branch = master) OR (type = pull_request)
      name: "Running lint"
      env:   TRAVIS_MODE=lint
      script:
        - yarn run lerna run eslint
    - stage: Tests
      if: (branch = master) OR (type = pull_request)
      name: "Running Flow type check"
      env:   TRAVIS_MODE=flow
      script:
        - yarn run lerna run flow
    - stage: Tests
      if: (branch = master) OR (type = pull_request)
      name: "Running unit tests"
      env:   TRAVIS_MODE=unitTests
      script:
        - yarn run lerna run test
